name: Sync package.json to docs

on:
  push:
    branches: [reformat_electron] # 如果你的默认分支不是 main，请改成对应名字
    paths-ignore: # ❶ 避免因机器提交再次触发
      - "docs/package.json"
permissions: # ★ 新增：授予写入代码库权限
  contents: write
jobs:
  copy-and-commit:
    if: github.actor != 'github-actions[bot]' # ❷ 双保险，阻止递归
    runs-on: ubuntu-latest

    steps:
      # 1) 拉取代码
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 默认令牌即可推回仓库

      # 2) 复制前端静态资源到 ./docs
      - name: Copy site static files
        run: |
          mkdir -p docs
          cp -f package.json favicon.ico docs/          # 覆盖同名文件
          cp -r readme.assets docs/                     # 递归复制整个目录

      # 3) 若 docs 有变动就提交
      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 将 docs 整个目录加入暂存区（含新增、修改、删除）
          git add -A docs

          # 如果暂存区有变更则提交
          if ! git diff --cached --quiet; then
            git commit -m "chore: sync static files to docs [skip ci]"
            git push
          else
            echo "No changes detected; skip commit."
          fi
